Agregada la funcion del camino critico, retocado backend clases y carpetas
elias-gill-UNA/CAlendar pull request #22
Opened 2022-05-26 04:27 UTC by Elias-Gill

Funcion de camino critico funcional hecha por Andres, algunos retoques al backend, nuevas clases disponibles, poco retoque a las clases que ya existian, nombres de clases cambiados. Algunos archivo y carpetas se movieron para concordar mejor con la estructura del proyecto. Un mini test para el backend agregado. 

TODO: 
Solucionar la importacion de modulos desde modulos hijos (por eso python da asco gente, trucho es). Seguir probando integracion con el backend y continuar con el enorme trabajo que nos espera

2022-05-26 04:29 UTC, Elias-Gill commented
Churro lo que sos lgm

2022-05-27 14:12 UTC, RickyMorel requested changes
Codigo bastante limpio! Hace falta modificar algunas cositas nomas

2022-05-27 14:12 UTC, RickyMorel commented on src/informes/camino_critico.py
> +def __inicializar(listaActividades):
Cambiar nombre a `InicializarLista`

2022-05-27 14:12 UTC, RickyMorel commented on src/informes/tests/cam_critico.py
> +# actividad 0
Esto es temporal vd?

2022-05-27 14:12 UTC, RickyMorel commented on src/backend/dataBase/tests/test.py
> +from ....clases.actividades import Actividad
Este archivo `tests.py` es necesario?

2022-05-27 15:30 UTC, Elias-Gill commented on src/informes/tests/cam_critico.py
> +# actividad 0
eso es un test nomas, por eso estaba en la carpeta test

2022-05-27 15:33 UTC, Elias-Gill commented on src/informes/camino_critico.py
> +def __inicializar(listaActividades):
Ya esta

2022-05-27 15:34 UTC, Elias-Gill commented on src/backend/dataBase/tests/test.py
> +from ....clases.actividades import Actividad
Siempre es bueno tener tests, o sea, si es importante

2022-05-27 16:31 UTC, merged