Calendar adolfo
elias-gill-UNA/CAlendar pull request #8
Opened 2022-05-15 19:43 UTC by AFFG69

Este algoritmo calcula los dias de caen los feriados de cualquier año.

2022-05-15 23:51 UTC, elias-gill-UNA requested changes
Realizar los cambios que se piden, mas info reu de discord

2022-05-15 23:51 UTC, elias-gill-UNA commented on src/utilidades/calendario/calendario.py
> +        return True
camibiar el return para que parezca feriado

2022-05-15 23:51 UTC, elias-gill-UNA commented on src/utilidades/calendario/calendario.py
> +
hacer de cuenta que solo se va a llamar al modulo zeller y al modulo feriado desde afuera del modulo

2022-05-17 16:58 UTC, RickyMorel requested changes

2022-05-17 16:58 UTC, RickyMorel commented on src/utilidades/calendario/calendario.py
> +def feriado(año,mes,dia):
Si esta funcion retorna un TRUE/FALSE entonces se deberia llamar `EsFeriado`

2022-05-17 16:58 UTC, RickyMorel commented on src/utilidades/calendario/calendario.py
> +# muchas funciones al pedo
Poner solo comentarios descriptivos a la funcion

2022-05-17 16:58 UTC, RickyMorel commented on src/utilidades/calendario/calendario.py
> +def finSemana(año,mes,fecha):
Que hace esta funcion? Determina si es el fin de la semana actual?

2022-05-17 17:00 UTC, RickyMorel reviewed
Buen trabajo! Solo necesita algunas cositas

2022-05-18 16:05 UTC, closed without merging